# for training
RWIDTH: 416
RHEIGHT: 416
OWIDTH: 1280
OHEIGHT: 720
BATCH_SIZE: 32
LEARNING_RATE: 0.0001
MOMETNUM: 0.9
EARLY_STOP: 0.999
MODEL_SAVE_FOLDER: ''
MODEL_SAVE_NAME: ''
PRETRAINED_PATH: ''
N_EPOCHS: 1000
MILESTONES: [50, 100, 150]
IOU_THRESHOLD: 0.5
TRAINING_FOLDER: 'D:/Dataset/LPR_dataset/xml_2/'